services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: algotrader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - C:/pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d algotrader" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s    